import Head from "next/head";
import { useEffect, useState } from "react";
import {
  Cover,
  EmbeddedMap,
  FeedBack,
  Footer,
  SectionTitle,
  Gallery,
  Address,
  LeftHero,
  Services
} from "../components";
export default function Home() {
  const [windowSize, setWindowSize] = useState(379);
  useEffect(() => {
    setWindowSize(window.innerWidth);

    window.addEventListener("resize", setWindowSize(window.innerWidth));

    return () =>
      window.removeEventListener("resize", setWindowSize(window.innerWidth));
  }, []);

  return (
    <div>
      <Head>
        <title>All Star Nails | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* //cover */}
      <Cover />

      <div className="container mx-auto">
        {/* // Services    */}
        <SectionTitle text={"Our Services"} />
        <Services />

        {/* // About us */}
        <LeftHero
          title={"Why choosing us ?"}
          desc={
            "Whether you want to get a simple, classic manicure or personalized look for your nails, we're here for you. </br></br> One of the striking features about the All Star Nail salon is expert people and staff. The highly experienced and skilled technicians will help you to have most relaxing moments. </br></br>From hand and feet nail art to sugaring services, you can find an amazing range of services here."
          }
          imgUrl={"/landscape/23.jpg"}
        />

        {/* // Gallery */}
        <div className="d-flex flex-column justify-content-center align-items-center">
          <SectionTitle text={"Our recent works"}/>
          <Gallery />


        {/* // Client reviews */}
          <SectionTitle text={"What customer saying about us?"} />
			    <FeedBack />
			  </div>

        {/* // Card */}
        <Address
          address={"8373 Kingston Pike, Knoxville, TN"}
          tel={"Tel : (865) 693-4776"}
          openingHrs={"Hours : 9:30AM - 7:30PM"}
        />
        {/* // Map */}
        <EmbeddedMap/>
      </div>

      <Footer />
    </div>
  );
}
