import Head from 'next/head'
import Image from "next/image";
import { useEffect, useState } from "react";
import {
  Cover,
  EmbeddedMap,
  FeedBack,
  Footer,
  SectionTitle,
} from "../components";
import Address from "../components/Address/Address";
import HeroWithForm from "../components/Hero/HeroWithForm";
import LeftHero from "../components/Hero/LeftHero";
import Services from "../components/Services/Services";

export default function Home() {
  const [windowSize, setWindowSize] = useState(379);
  useEffect(() => {
    setWindowSize(window.innerWidth);

    window.addEventListener("resize", setWindowSize(window.innerWidth));

    return () =>
      window.removeEventListener("resize", setWindowSize(window.innerWidth));
  }, []);
  const map =
    "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12923.795614560004!2d-84.0582226!3d35.9237507!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xbc97be0665e11f1d!2sAll%20Star%20Nails!5e0!3m2!1sde!2sus!4v1644092287988!5m2!1sde!2sus";
  return (
    <div>
      <Head>
        <title>All Star Nails | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* //cover */}
      <Cover />
      {/* // address */}
      <div className="container mx-auto">
        {/* // Our Services    */}
        <SectionTitle text={"Our Services"} />
        <Services />
        {/* // Why choosing us */}
        <LeftHero
          title={"Why choosing us ?"}
          desc={
            "Whether you want to get a simple, classic manicure or personalized look for your nails, we're here for you. </br></br> One of the striking features about the All Star Nail salon is expert people and staff. The highly experienced and skilled technicians will help you to have most relaxing moments. </br></br>From hand and feet nail art to sugaring services, you can find an amazing range of services here."
          }
          imgUrl={"/portrait/19.jpg"}
        />
        {/* // client comment */}
        <div className="d-block">
          <Image
            width={windowSize < 400 ? "400" : "1280"}
            height={windowSize < 400 ? "600" : "720"}
            src={windowSize < 400 ? "/portrait/6.jpg" : "/landscape/22.jpg"}
            alt="customer reviews"
            className="mx-auto"
          />
        </div>
        <FeedBack />

        {/* address */}
        <Address
          address={"8373 Kingston Pike, Knoxville, TN"}
          tel={"Tel : (865) 693-4776"}
          openingHrs={"Hours : 9:30AM - 7:30PM"}
        />
        {/* // map */}
        <EmbeddedMap src={map} />
      </div>
      <Footer />
    </div>
  );
}
